### ISSUE TITLE
Facebook: Live authentication not possible

### ISSUE THREAD

**Issue by nichoio** [rappertomate/Reddit-Recommender#4]
It seems that localhost and http (instead of https) is not supported for oauth flow.
That means that we cannot ask users for consent via webinterface in order to analyze their facebook likes.
Alternative proposal:
- We predefine users and get their access tokens programmatically (which is possible)
- Those predefined users could be accounts we created solely for this assignement and which could be used by the staff (so we would give the login data for those accounts to the staff and they can like stuff and see how it changes the recommendations)

See also:
https://stackoverflow.com/questions/13376710/facebook-app-domain-name-when-using-localhost
https://stackoverflow.com/questions/52850733/redirect-uris-are-not-allowed-in-facebook-valid-oauth-redirect-uris

**Comment by moelliDo** [comment]
The Facebook developer page offers the possibility to add generic test-users which you can use to log into Facebook and like/comment/post things. We could give these test users to the chair so that they can examine the impact of liking/commenting/posting things on our recommender-system. This seems to be a suitable workaround.

**Comment by moelliDo** [comment]
Link to extend the validity of access tokens: 
https://developers.facebook.com/tools/debug/accesstoken/
